.PHONY: cov

cov: all
	./raycaster &&\
	lcov --capture --directory . --output-file coverage.info &&\
	genhtml coverage.info --output-directory html

DEBUG=-O0 -g
CFLAGS+=-Wall -Wextra -Werror -std=c99 -pedantic -pipe $(DEBUG) --coverage
LDFLAGS=-lm --coverage

include Makefile.common
