#ifndef _CORE_PRIVATE_H
#define _CORE_PRIVATE_H

#ifdef COUNTERS

#define STO(v)		cnt.sto += (v)
#define CMP(v)		cnt.cmp += (v)
#define ADD(v)		cnt.add += (v)
#define MUL(v)		cnt.mul += (v)
#define ABS(v)		cnt.abs += (v)
#define SQR(v)		cnt.sqr += (v)
#define TRG(v)		cnt.trg += (v)
#define IDX(v)		cnt.idx += (v)
#define NEG(v)		cnt.neg += (v)

#define IS_PNT(v)	cnt.is_pnt += (v)
#define IS_VEC(v)	cnt.is_vec += (v)
#define IS_0(v)		cnt.is_0   += (v)
#define IS_1(v)		cnt.is_1   += (v)
#define IS_ORT(v)	cnt.is_ort += (v)
#define FN_LEN(v)	cnt.fn_len += (v)
#define FN_DOT(v)	cnt.fn_dot += (v)
#define FN_VEC(v)	cnt.fn_vec += (v)
#define FN_SCL(v)	cnt.fn_scl += (v)
#define FN_1(v)		cnt.fn_1   += (v)
#define FN_ADD(v)	cnt.fn_add += (v)
#define FN_SUB(v)	cnt.fn_sub += (v)
#define FN_X(v)		cnt.fn_x   += (v)
#define FN_HMG(v)	cnt.fn_hmg += (v)
#define FN_MXC(v)	cnt.fn_mxc += (v)
#define FN_MXM(v)	cnt.fn_mxm += (v)
#define FN_T(v)		cnt.fn_t   += (v)
#define FN_RTX(v)	cnt.fn_rtx += (v)
#define FN_RTY(v)	cnt.fn_rty += (v)
#define FN_RTZ(v)	cnt.fn_rtz += (v)
#define FN_ROT(v)	cnt.fn_rot += (v)
#define FN_TSL(v)	cnt.fn_tsl += (v)
#define FN_FEQ(v)	cnt.fn_feq += (v)

#else  /* COUNTERS */

#define STO(v)
#define CMP(v)
#define ADD(v)
#define MUL(v)
#define ABS(v)
#define SQR(v)
#define TRG(v)
#define IDX(v)
#define NEG(v)

#define IS_PNT(v)
#define IS_VEC(v)
#define IS_0(v)
#define IS_1(v)
#define IS_ORT(v) 
#define FN_LEN(v) 
#define FN_DOT(v) 
#define FN_VEC(v) 
#define FN_SCL(v) 
#define FN_1(v) 
#define FN_ADD(v) 
#define FN_SUB(v) 
#define FN_X(v) 
#define FN_HMG(v) 
#define FN_MXC(v)
#define FN_MXM(v)
#define FN_T(v)
#define FN_RTX(v)
#define FN_RTY(v)
#define FN_RTZ(v)
#define FN_ROT(v)
#define FN_TSL(v)
#define FN_FEQ(v)

#endif /* COUNTERS */

#endif /* _CORE_PRIVATE_H */
